name = "extraordinary_energy_modern"
author = "Sponeru"
version = "1.0.7"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f77ffa0f81e4e16d6688acbae035daf0ec2d3a5e35a57851892d65b2109092f6"

[versions]
forge = "47.4.10"
minecraft = "1.20.1"
