name = "extraordinary_energy_modern"
author = "Sponeru"
version = "1.0.7"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5205da049c359107294da7ed305f3e1e46e1ba9721de56fb098f8efca19158bf"

[versions]
forge = "47.4.10"
minecraft = "1.20.1"
