name = "extraordinary_energy_modern"
author = "Sponeru"
version = "1.0.7"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ebaf81d8f36a35f65b54929367fcb085dbd0215d2ffd42c2696ad959beea1a55"

[versions]
forge = "47.4.10"
minecraft = "1.20.1"
