ServerEvents.tags("item", event => {
    event.remove("forge:ores/redstone", 'denseores:dense_redstone_ore')
    event.remove("forge:ores/redstone", 'denseores:dense_deepslate_redstone_ore')
    event.remove("forge:ores/diamond", 'denseores:dense_diamond_ore')
    event.remove("forge:ores/diamond", 'denseores:dense_deepslate_diamond_ore')
    event.remove("forge:ores/emerald", 'denseores:dense_emerald_ore')
    event.remove("forge:ores/emerald", 'denseores:dense_deepslate_emerald_ore')
    event.remove("forge:ores/lapis", 'denseores:dense_lapis_ore')
    event.remove("forge:ores/lapis", 'denseores:dense_deepslate_lapis_ore')
    event.remove("forge:ores/coal", 'denseores:dense_coal_ore')
    event.remove("forge:ores/coal", 'denseores:dense_deepslate_coal_ore')
    event.remove("forge:ores/copper", 'denseores:dense_copper_ore')
    event.remove("forge:ores/copper", 'denseores:dense_deepslate_copper_ore')
    event.remove("forge:ores/gold", 'denseores:dense_gold_ore')
    event.remove("forge:ores/gold", 'denseores:dense_deepslate_gold_ore')
    event.remove("forge:ores/iron", 'denseores:dense_iron_ore')
    event.remove("forge:ores/iron", 'denseores:dense_deepslate_iron_ore')
})