
#Evolved Mekanism Extras Tank Capacity Config
[tank]
	#Chemical tank capacity (mB).
	#Range: 1 ~ 9223372036854775807
	AbsoluteOverclockedFactories = 3024000
	#Chemical tank capacity (mB).
	#Range: 1 ~ 9223372036854775807
	SupremeQuantumFactories = 4116000
	#Chemical tank capacity (mB).
	#Range: 1 ~ 9223372036854775807
	CosmicDenseFactories = 5376000
	#Chemical tank capacity (mB).
	#Range: 1 ~ 9223372036854775807
	InfiniteMultiversalFactories = 6804000
	#Chemical tank capacity (mB).
	#Range: 1 ~ 9223372036854775807
	AbsoluteOverclockedInfusingFactory = 14400000
	#Chemical tank capacity (mB).
	#Range: 1 ~ 9223372036854775807
	SupremeQuantumInfusingFactory = 19600000
	#Chemical tank capacity (mB).
	#Range: 1 ~ 9223372036854775807
	CosmicDenseInfusingFactory = 25600000
	#Chemical tank capacity (mB).
	#Range: 1 ~ 9223372036854775807
	InfiniteMultiversalInfusingFactory = 32400000

